const mongoose=require("mongoose");
const userSchema=new mongoose.Schema(
    {
        firstName:{
            type:String,
            required:true,
            trim:true
        },
        lastName:{
            type:String,
            required:true,
            trim:true
        },
        email:{
            type:String,
            required:true,
            trim:true
        },
        password:{
            type:String,
            required:true
        },
        confirmpassword:{
            type:String,
            required:true
        },
        contactNumber:{
            type:Number,
            required:true
        },
        accountType:{
            type:String,
            enum:["Admin","Student","Instructor"],
            required:true
        },
        token:{
            type:String,
        },
        resetPasswordExpire:{
            type:Date,
        },
        additionalDetail:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"Profile"
        },

        courses:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"Course",

            }
        ],
        Image:{
            type:String,
          required:true,
        },
        coursesProgress:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"CourseProgress"
            }
        ]

    }
);
module.exports=mongoose.model("User",userSchema);